### ISSUE TITLE
Can't pip install on a new env (without Cython)

### ISSUE THREAD

**Issue by zachmoshe** [VKCOM/YouTokenToMe#94]
I have a project where YouTokenToMe is one of the dependencies and get a `No module named 'Cython'` when trying to install YouTokenToMe as a dependency.

I saw that `setup.cfg` uses Cython internally, so it's not a matter of `install_requires`. pip fails when it starts running the file because `Cython` doesn't exist.

Obviously a workaround is to just install Cython before in the environement, but that's hacky. I rather have YouTokenToMe declare that it needs Cython. Is that even possible?

**Comment by gbeckenkamp** [comment]
Should be fixed by https://github.com/VKCOM/YouTokenToMe/pull/103

**Comment by cdeln** [comment]
@yutkin Do you have time to take a look at this issue? It's a trivial fix, and it affects downstream package consumers, so a merge is heavily appreciated. Thanks!

**Comment by TechInterMezzo** [comment]
This problem is still present for me on Windows 10. It's a pity that this project seems to be abandoned.

**Comment by Manamama** [comment]
Still present in Ubuntu 20

```
pip show cython
Name: Cython
Version: 3.0.7
Summary: The Cython compiler for writing C extensions in the Python language.
Home-page: https://cython.org/
Author: Robert Bradshaw, Stefan Behnel, Dag Seljebotn, Greg Ewing, et al.
Author-email: cython-devel@python.org
License: Apache-2.0
... 
Requires: 
Required-by: fairseq, TTS

```

but

```
        File "/tmp/pip-build-env-gdhr_y3w/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-gdhr_y3w/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-gdhr_y3w/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 5, in <module>
      ModuleNotFoundError: No module named 'Cython'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.

```

Using its apt version does not help, either.
